[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = [
  'pnpm install --frozen-lockfile',
  'npx prisma generate'
]

[phases.build]
cmds = ['pnpm run build']

[start]
cmd = 'npx prisma migrate deploy && pnpm run start:prod'
