[phases.setup]
nixPkgs = ["nodejs_20"]
aptPkgs = []

[phases.install]
cmds = ["npm install -g pnpm", "cd server && pnpm install"]

[phases.build]
cmds = ["cd server && pnpm prisma:generate && pnpm build"]

[start]
cmd = "cd server && pnpm start:prod"
