[phases.setup]
nixPkgs = ['nodejs-20_x']

[phases.install]
cmds = ['pnpm install']

[phases.build]
cmds = [
  'pnpm run build',
  'npx prisma generate',
  'npx prisma migrate deploy'
]

[start]
cmd = 'pnpm run start:prod'
