[phases.setup]
nixPkgs = ["nodejs_20", "pnpm"]

[phases.install]
cmds = ["cd server && pnpm install"]

[phases.build]
cmds = ["cd server && pnpm prisma:generate && pnpm build"]

[start]
cmd = "cd server && pnpm start:prod"
